### ISSUE TITLE
Current sync sub-task assignment may be skewed

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#90] opened 2023-11-21 16:23 UTC
The sync sub-tasks were assigned during initialization, where if some sub-tasks read from a slow peer, the sub-tasks may be much slower than others.  As a result, other sub-tasks can finish early without helping other sub-tasks, resulting in longer sync time.

**Comment by qizhou** [comment] 2023-11-21 16:24
<img width="1735" alt="image" src="https://github.com/ethstorage/es-node/assets/2541286/88d27196-a042-486b-b886-6e09ae73e41d">

An example can be found here, where initial sub-tasks are 32.

**Comment by qzhodl** [comment] 2023-11-22 03:19
Seems like we may need to get a random idle peer in getIdlePeerForTask()?

**Comment by ping-ke** [comment] 2023-11-22 07:01
One peer's slowness does not cause that, it is caused by how we assign peers to tasks. each time we have a peer available, we will assign it to the head tasks. for example, if 3 peers can serve 9 tasks at the same time. Then tasks 0 - 8 finish first, then tasks 9 - 17, and tasks 18 - 26. and finally, we will see 5 tasks left. and the parallelization is not good for the last few tasks. 

```
	for _, t := range s.tasks {
		maxRange := s.syncerParams.MaxRequestSize / ethstorage.ContractToShardManager[t.Contract].MaxKvSize() * 2
		for _, stask := range t.SubTasks {
			st := stask
			if st.done {
				continue
			}
			// Skip any tasks already running
			if st.isRunning {
				continue
			}
			pr := s.getIdlePeerForTask(t)
			if pr == nil {
				continue
			}

```

Solution:
1. split to more tasks with a smaller blob count (add max blob count with value like 32768), so the last few tasks may finish within 1 hour. 
2. change the way assigning peers to tasks.

**Closed** 2023-12-12 01:42 UTC
